### ISSUE TITLE
LinkageError ProtocolLib 3.6.5

### ISSUE THREAD

**Issue by MatteCarra** [aadnk/ProtocolLib#100]
I'm getting this exception http://pastebin.com/aTa4NLh5
Jar is not linked.
I'm using latest spigot build.

**Comment by dmulloy2** [comment]
Are you using NoCheatPlus?

**Comment by MatteCarra** [comment]
Yes

**Comment by dmulloy2** [comment]
The issue is definitely related to NCP, although I've never been able to figure out exactly how. Apparently, newer builds of it don't have this issue though. Try them.
