### ISSUE TITLE
Exception (NullPointerException) at PacketPlayOutChat

### ISSUE THREAD

**Issue by ReedFlake** [aadnk/ProtocolLib#101]
I'm creating a plugin that change messages with ProtocolLib (latest) and Spigot 1.8.8, but i received an exception from ProtocolLib.

Exception at Pastebin: http://pastebin.com/i876uxAL
Line number 75:
```java
final Object data = this.parser.parse( componets.read( 0 ).getJson() );
```

**Comment by dmulloy2** [comment]
This is an issue with how Spigot sends custom JSON messages. At the bottom of the stack it shows the fields in the packet. a is the internal Minecraft chat components, while components is Spigot's. You'd  have to read the second field in the packet and cast it to BaseComponent[] to work with it.

**Comment by ReedFlake** [comment]
Thank you, i'm fixed it now.
