### ISSUE TITLE
[Paper 1.9.2] Registering a client use entity packet handler will interfere with combat.

### ISSUE THREAD

**Issue by kosakriszi** [aadnk/ProtocolLib#104]
Tested with ProtocolLib build 269

Registering any packet handler for the use entity packet, even an empty handler, will effectively prevent the player from landing critical hits and power attacks on entities.

**Comment by dmulloy2** [comment]
The packet may be async but I'm not sure. Try creating the packet adapter with the async option:

````java
manager.addPacketListener(new PacketAdapter(PacketAdapter.params()
    .plugin(plugin)
    .types(PacketType.Play.Client.USE_ENTITY)
    .optionAsync() {
});
````

**Comment by kosakriszi** [comment]
I was already registering the adapter as async, except I was doing it through
_manager.getAsynchronousManager().registerAsyncHandler(PacketAdapter).startSync()_
Registering it through the more builder-like approach worked well for me!

In hind sight, I most likely shot myself in the foot by starting it synchronously.
I have solved my issue, thank you for your help!
