### ISSUE TITLE
The Sleep Animation causes a FieldAccessException!

### ISSUE THREAD

**Issue by Blockhead7360** [aadnk/ProtocolLib#111]
Hello! I know this is kind of a duplicate issue, but I haven't really found an answer that worked for me. Here is my code (taken from the SleepAnimation.java):

`
     private void playSleepAnimation(Player asleep) {
		final PacketContainer bedPacket = manager.createPacket(PacketType.Play.Server.BED);
		final Location loc = asleep.getLocation();
		// http://wiki.vg/Protocol#Use_Bed
		bedPacket.getIntegers().write(0, asleep.getEntityId());

		bedPacket.getBlockPositionModifier().
		write(1, new BlockPosition(loc.getBlockX(), loc.getBlockY() + 1, loc.getBlockZ()));

		this.broadcastNearby(asleep, bedPacket);
	}`

I keep getting a FieldAccessException! Why?

**Comment by Blockhead7360** [comment]
Do I have to store everything in "write(0,..."?

**Comment by dmulloy2** [comment]
Can you provide the exception?

**Comment by Blockhead7360** [comment]
The stack trace is on this thread: https://bukkit.org/threads/sleeping-animation-throws-a-fieldaccessexception-protocollib.425550/

**Comment by dmulloy2** [comment]
Change the index in write() to 0. Indexes start with 0 in Java.

**Comment by Blockhead7360** [comment]
I tried:

`private void playSleepAnimation(Player asleep) {
		PacketContainer bedPacket = manager.createPacket(PacketType.Play.Server.BED);
		int x = asleep.getLocation().getBlockX();
		int y = asleep.getLocation().getBlockY();
		int z = asleep.getLocation().getBlockZ();
		
		bedPacket.getIntegers().write(0, asleep.getEntityId());
		bedPacket.getBlockPositionModifier().write(0, new BlockPosition(x, y, z));
		
		this.broadcastNearby(asleep, bedPacket);
		
	}`

It doesn't throw an error, but it doesn't do **anything**

**Comment by Blockhead7360** [comment]
@dmulloy2 
I tried:

`
private void playSleepAnimation(Player asleep) {
PacketContainer bedPacket = manager.createPacket(PacketType.Play.Server.BED);
int x = asleep.getLocation().getBlockX();
int y = asleep.getLocation().getBlockY();
int z = asleep.getLocation().getBlockZ();

    bedPacket.getIntegers().write(0, asleep.getEntityId());
    bedPacket.getBlockPositionModifier().write(0, new BlockPosition(x, y, z));

    this.broadcastNearby(asleep, bedPacket);

}`
It doesn't throw an error, but it doesn't do anything

**Comment by dmulloy2** [comment]
Two things I can think of:
1. Try adding 1 to the Y coordinate
2. You might need an actual bed

**Comment by dmulloy2** [comment]
Any more info on this?

**Comment by ernierock** [comment]
Hey, I've been having the same problem for a long time and just did some more tests. It works when standing on top of a bed, but not anywhere else. Sadly it seems like minecraft enforces the need of a bed now.

**Comment by ernierock** [comment]
I've found the issue. When you want to get "fake sleep", giving the location of the head part of a bed instead of the player's location seems to fix the issue, even if the bed is far away. The player will remain "sleeping" in his location and won't be teleported to the bed.

Previously the "head part of the bed location" was where you'd go to sleep, this is now more literally the actual head part of a bed.
