### ISSUE TITLE
NAMED_SOUND_EFFECT - Problem with writing string into this packet

### ISSUE THREAD

**Issue by piter909** [aadnk/ProtocolLib#112]
Hello,
I found bug or mistake in ProtocolLib with .getStrings() in "PacketType.Play.Server.NAMED_SOUND_EFFECT".
When I am trying to write string into this packet, I am getting this exception:
http://pastebin.com/UhWJ7z0e
On wiki, as I can see, string exists:
http://wiki.vg/Protocol#Named_Sound_Effect
My code:
http://pastebin.com/jxNRjLnR 
I am using latest release of ProtocolLib for 1.10 (July) from SpigotMC.
My last update of spigot was ~2 weeks ago (1.10.2).

I hope it is just me, if not - please, fix it as fast as it is possible. I need it a lot :x

**Comment by dmulloy2** [comment]
````FieldAccessException: No field with type java.lang.String exists in class PacketPlayOutNamedSoundEffect.````

The modifier you're looking for is [````packet.getSoundEffects()````](http://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/events/PacketContainer.html#getSoundEffects())

**Comment by piter909** [comment]
I was trying using getSoundEffects() method (look into my code).
It was not working, player is not hearing any sound. What I am doing wrong?

**Comment by dmulloy2** [comment]
The constructor of the named sound effect packet looks like this:
````java
    public PacketPlayOutNamedSoundEffect(SoundEffect soundeffect, SoundCategory soundcategory, double d0, double d1, double d2, float f, float f1) {
        Validate.notNull(soundeffect, "sound", new Object[0]);
        this.a = soundeffect;
        this.b = soundcategory;
        this.c = (int) (d0 * 8.0D);
        this.d = (int) (d1 * 8.0D);
        this.e = (int) (d2 * 8.0D);
        this.f = f;
        this.g = f1;
    }
````

So yes, you have to multiply the coordinates by 8 and provide a sound category.
