### ISSUE TITLE
Request: Add getItemListModifier() for window items

### ISSUE THREAD

**Issue by Jalau11** [aadnk/ProtocolLib#114]
The window items packet now contains a List<ItemStack> b instead of an array ItemStack[]. Adding a getItemListModifier() and write method would prevent the common user from needing to refer to reflection to modify the packet.

**Comment by dmulloy2** [comment]
I agree that it should be added, but not with the rationale. If you're meddling with packets, you should be referring to the MC source.

**Comment by dmulloy2** [comment]
Added in https://github.com/dmulloy2/ProtocolLib/commit/7a9b9afe2e439a4f50b66781adab474896072674
