### ISSUE TITLE
MPets Not working with ProtocolLib

### ISSUE THREAD

**Issue by Fonzee9** [aadnk/ProtocolLib#116]
05.12 19:12:48 [Server] WARN java.lang.NoSuchFieldException: networkManager
05.12 19:12:48 [Server] WARN at java.lang.Class.getDeclaredField(Unknown Source)
05.12 19:12:48 [Server] WARN at com.kirelcodes.miniaturepets.utils.ף.ח(NMSClassInteracter.java:161)
05.12 19:12:48 [Server] WARN at com.kirelcodes.miniaturepets.utils.ף.getDeclaredField(NMSClassInteracter.java:150)
05.12 19:12:48 [Server] WARN at com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.טש.ח(PacketInjector.java:47)
05.12 19:12:48 [Server] WARN at com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.טש.addPlayer(PacketInjector.java:28)
05.12 19:12:48 [Server] WARN at com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.ם.onPlayerJoin(CoreListener.java:333)
05.12 19:12:48 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05.12 19:12:48 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
05.12 19:12:48 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05.12 19:12:48 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
05.12 19:12:48 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
05.12 19:12:48 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
05.12 19:12:48 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
05.12 19:12:48 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:334)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
05.12 19:12:48 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
05.12 19:12:48 [Server] WARN at java.lang.Thread.run(Unknown Source)

**Comment by dmulloy2** [comment]
*sigh

This is an error with MPets and has nothing to do with ProtocolLib
