### ISSUE TITLE
Horse Spawning Disabled by Protocollib?

### ISSUE THREAD

**Issue by LeonTG77** [aadnk/ProtocolLib#117]
So I followed this and made a quick simple plugin to see what plugin disables horse spawning 
https://bukkit.org/threads/how-to-get-what-plugin-is-cancelling-an-event.146888/

and I get in my chat that "ProtocolLib v3.6.5" is the one cancelling the event for Horses to spawn

Any idea why and how to fix?

**Comment by MiniDigger** [comment]
did you copied the event handler that is marked as "// For testing" too? if so, don't do that.

**Comment by LeonTG77** [comment]
I did not copy that part

**Comment by dmulloy2** [comment]
I know Mojang disabled horses on old worlds, but I can say with certainty that ProtocolLib doesn't mess with spawning.
