### ISSUE TITLE
Wrong packet IDs for NamedSoundEffect and upwards 

### ISSUE THREAD

**Issue by nullEuro** [aadnk/ProtocolLib#120]
The packet id for `NamedSoundEffect` is actually `0x46` instead of `0x47`. All packets after this one have their ids shifted by one. Unfortunately I need to work with raw IDs in my current project because it involves writing packets to a file.

**Comment by dmulloy2** [comment]
I just fixed this about an hour ago

**Comment by nullEuro** [comment]
Nice. Keep up the good work, love your plugin!
