### ISSUE TITLE
Ancient Gson version?

### ISSUE THREAD

**Issue by dadus33** [aadnk/ProtocolLib#121]
Hello!
Firstly, I'm sorry I don't respect the issue template, but I really think it would be much easier for both of everyone if I'd just link you to the spigot post that made me post this: https://www.spigotmc.org/threads/chatitem-display-items-in-chat.126220/page-12#post-2118949
I'm rather certain this is not a ProtocolLib issue, as the last modification to the ComponentParser was on the 6th of August, and I think I'm right in my belief of how the getConstructor method works. However, can you please enlighten me on what the issue might be? From the looks of it, JsonReader was indeed found at the requested location, but it's constructor didn't match. I've tried diving deep into Gson's history back to 2013, but I still couldn't find any version that didn't have that constructor. So what might the problem be?
Again, sorry to post it in the Issues section, but I think that solving this might actually contribute to the development of ProtocolLib.

**Comment by dadus33** [comment]
Thanks for solving that! So in the end, I was wrong about how the getConstructor method works? I thought you could supply an extending class as an argument and it would still find it. For instance, running getConstructor(StringReader.class) should return the same as getConstructor(Reader.class), as StringReader extends Reader. But looks like I was wrong...

**Comment by dmulloy2** [comment]
I guess I assumed the same as well. Either that or I didn't look at the documentation close enough lol

**Comment by dadus33** [comment]
I've read the docs too (https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getConstructor(java.lang.Class...)), but it doesn't explain that there.
