### ISSUE TITLE
ProtocolManager#getProtocolVersion() allways returning 2?

### ISSUE THREAD

**Issue by dadus33** [aadnk/ProtocolLib#123]
The title pretty much sums it up. All calls to getProtocolVersion() return 2, no matter what version the client actually is. I thougth the issue might be the fact that I'm using ProtocolSupport to supply backwards compatibility for older versions. My server is 1.9.4 and connected clients are 1.8.X -1.9.X. From wiki.vg, I've seen that all 1.8 clients (not snapshots) have protocol version 47. However, the call always returns 2.

**Comment by MiniDigger** [comment]
it just returns the current version: https://github.com/aadnk/ProtocolLib/blob/051989a396e8484e3c1b6f1af3915eb7044ddc54/modules/ProtocolLib/src/main/java/com/comphenix/protocol/injector/player/ProxyPlayerInjectionHandler.java#L156

**Comment by dadus33** [comment]
Oh, I see. So it doesn't actually return the version for the player's client... Well I guess that should be addressed as an issue then?

**Comment by dmulloy2** [comment]
The method only really worked on the protocol hacks, when there was an easy way to determine the player's version (NetworkManager#getVersion() or something to that effect). Plugins like ProtocolSupport and ViaVersion do their own non-standard behavior that ProtocolLib doesn't explicitly support.
