### ISSUE TITLE
License

### ISSUE THREAD

**Issue by OsipXD** [aadnk/ProtocolLib#125]
Hello! 
GNU GPL contains these lines: 

> This General Public License does not permit incorporating your program into
> proprietary programs.

May be better to use LGPLv2 or higher?

**Comment by MiniDigger** [comment]
good luck trying to relicence this, lol

**Comment by dmulloy2** [comment]
Re-licensing would be pretty much impossible even if I saw the need to. You really shouldn't be including ProtocolLib itself in your projects, let alone proprietary projects.

**Comment by OsipXD** [comment]
It means that many premium plugins on SpigotMC (like a [this](https://www.spigotmc.org/resources/2900/), [this](https://www.spigotmc.org/resources/6442/) and [this](https://www.spigotmc.org/resources/1368/)) violate the license when using ProtocolLib in plugins that are not under the GNU GPL?
The same applies to the free plugins.

**Comment by dmulloy2** [comment]
You can call the API of something without "incorporating" it (actually adding ProtocolLib's classes to their project), so they're just fine with the license.

**Comment by mastercoms** [comment]
Using the import statement links an application to the library. Under the GPL, applications linking to a library are considered a derivative work of both the application and the library. So if a plugin uses this library, it must be licensed under the GPL.

The way the Bukkit project gets around this (despite the Bukkit API being GPL'd) is that at runtime, plugins use the LGPL-licensed CraftBukkit.

**Comment by MiniDigger** [comment]
if you want to go that route, good luck, bukkit is gpl too.

**Comment by mastercoms** [comment]
But at runtime, plugins an implementation of Bukkit, commonly CraftBukkit, which is licensed under the LGPL.

**Comment by MiniDigger** [comment]
> Using the import statement links an application to the library
you import bukkit and thus are linked to it and its license.

**Comment by mastercoms** [comment]
Java performs this linking at runtime, so it is entirely dependant on the licensing of the implementation.
