### ISSUE TITLE
WrappedDataWatcher not initialising properly

### ISSUE THREAD

**Issue by NecroneUnderscore** [aadnk/ProtocolLib#128]
SPIGOT 1.11.2 Latest w/ Protocollib latest development build

`
WrappedDataWatcher watcher = new WrappedDataWatcher();
watcher.setObject(13, ((byte) 127));
`
Description and relevant errors: After trying to initialise a WrappedDataWatcher using the no parameter constructor, any use of a setObject method triggers the exception below. Providing the handle myself seems to work, but is not usable in my situation, I need to use a watcher for a fake entity. 

throw new IllegalArgumentException("You cannot register objects without a watcher object!");

**Comment by dmulloy2** [comment]
You need to create a watcher object: http://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/wrappers/WrappedDataWatcher.WrappedDataWatcherObject.html

**Comment by NecroneUnderscore** [comment]
I could've sworn it wasn't necessary in the past, and saw a fair few posts around the spigot forums using it as such. Thanks for the assistance!

**Comment by dmulloy2** [comment]
Yeah it used to not be necessary, you can thank Mojang's changes in 1.9.
