### ISSUE TITLE
GPL Licensing Question of ProtocolLib and PacketWrapper

### ISSUE THREAD

**Issue by Ghostium** [aadnk/ProtocolLib#130]
Hey,
I'm using both ProtocolLib and PacketWrapper for my Spigot plugins. After revisiting the source of packet wrapper I noticed that both the ProtocolLib and PacketWrapper project are under a GPL license.

If I understand it correctly, code that is linking to one of those projects needs to be disclosed with a GPL compatible license. I would like to keep my plugins closed source, so I would like to ask you if you cloud switch to a more permissive license like MIT. That would be very nice of you :)

**Comment by dmulloy2** [comment]
This has been discussed in the past. The consensus was pretty much that's it's not an issue , but if it was, changing the license would be nigh impossible

**Comment by Ghostium** [comment]
Thank you for your fast response. That answers my question.

**Comment by MiniDigger** [comment]
you link to bukkit, which is gpl anyways. nobody cared about that in the past tho.

**Comment by Ghostium** [comment]
Well, ProtocolLib is using NMS classes from the notchian server, which of course is itself under a proprietary license. I think besides Mojang/Microsoft none could practically enforce licenses for their Bukkit plugins in court if we view it this way.  Plugins that only depend on the Bukkit-API and don't use the Craftbukkit stuff may have luck with that, but I wouldn't bet on that.

**Comment by dmulloy2** [comment]
The Bukkit API itself [is GPL](https://github.com/Bukkit/Bukkit/blob/master/LICENCE.txt). But yeah that's ultimately what it comes down to, no one really has the time/resources/desire to take you to court over some plugins.
