### ISSUE TITLE
Building ProtocolLib 4.2.1

### ISSUE THREAD

**Issue by dadus33** [aadnk/ProtocolLib#131]
Hey! I just wanted to know how can I build ProtocolLib 4.2.1 for 1.8. The latest version does NOT seem to work with the first revision of 1.8. https://pastebin.com/raw/gFNiaxvh
Thanks!

**Comment by dmulloy2** [comment]
Try the latest dev build, I remember fixing that error recently

**Comment by dadus33** [comment]
Okay, thanks, but I'd still like to know how can I build the 4.2.1 version myself when needed.

**Comment by MiniDigger** [comment]
you use git to checkout the tag/commit that corresponds to that version and then run maven

**Comment by dadus33** [comment]
well yes, but that commit is outdated. some fixes added in the later versions are not included.

**Comment by MiniDigger** [comment]
well, duh, if you want later fixes you use later version.

**Comment by dadus33** [comment]
Nevermind, turns out I was a bit stupid.
