### ISSUE TITLE
LinkageError

### ISSUE THREAD

**Issue by xXAlex10Xx** [aadnk/ProtocolLib#138]
Hey,
on my server a linkage error occures on nearly 50% of the nightly restarts. I cannot figure out why, so I am opening an issue here.

Plugins used:
AAC
AAC+
ConditionalCommands
CratesPlus
EnderContainers
EssentialsX
HolographicDisplays
Shopkeepers
ViaVersion
WorldEdit
WorldGuard

and a few self-written plugins.

I don't think, that this error is caused by other plugins. Maybe due to the daily backup, which is made before the restart?
But this error occures only on ProtocolLib.

I hope you can help me with this.

Thanks in advance.

**Comment by MiniDigger** [comment]
and you provide a provide a crash log?

**Comment by xXAlex10Xx** [comment]
Well, i did not save a full error log. I could send one, when it happens next. I just know, that this is the main line: java.lang.LinkageError: com/comphenix/protocol/events/PacketContainer

I'll upload the full error, when it happens next.

I can't look up, because i have to load a backup every time this happens. This error makes all other plugins go crazy - nothing works.

**Comment by ljacqu** [comment]
The full error should help find out what plugin is causing this, hopefully. LinkageError is typically a compatibility issue: code was compiled against a ProtocolLib version but on the server there is an older version in which some of the features used are not yet present.
Failing that, you could also remove plugins to determine which one is causing the issue.

**Comment by xXAlex10Xx** [comment]
@ljacqu 
How could it be, that just in some of the cases this error occures?
Same setup, other restart and it works. A restart later my console gets spammed with errors and nothing works.
Usually i compile with the current version from maven and I updated ProtocolLib recently on the server, so this should work, i think?
But I'll take a look on the version against which it is compiled and check which is on the server.

Thanks :p

**Comment by xXAlex10Xx** [comment]
@ljacqu 
The full error is pasted here:
https://hastebin.com/kutozudume.pl
The error is thrown in my permission-system.
ProtocolLib-Version: 4.3.0
Compiled against: 4.1.0
Updated dependencies, but the error is still thrown.
In like 10% of the restarts, randomly, when a player joins (and my permissionsystem tries to modify packets) the plugin crashes, and due to the injection to the playerobject, all other plugins which use p.getPermission() won't work too.

So i catched the error now in the join-event aaand:
13.07 01:35:24 [Server] INFO UUID of player KennyTV is a8179ff3-c201-4a75-bdaa-9d14aca6f83f
13.07 01:35:24 [Server] INFO Uhm? ProtocolLib-Error? Restarting...
13.07 01:35:24 [Server] INFO Stopping server

But is there still an option to fix it probably?

**Comment by dmulloy2** [comment]
Okay this one is actually relatively simple to solve. Some linkage errors can be next to impossible to solve. The permissions plugin just needs to be compiled against 4.3.0 and you'll be golden.

**Comment by xXAlex10Xx** [comment]
@dmulloy2 
I already did, when @ljacqu mentioned it. But the error still occures sometimes.

**Comment by ForceUpdate1** [comment]
Hello,
I have the same problem too.

**Comment by kamcio96** [comment]
Same here. Occurs after few hours after server start

**Comment by kamcio96** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/437
