### ISSUE TITLE
Error 1.8

### ISSUE THREAD

**Issue by heroeminecratti** [aadnk/ProtocolLib#139]
virtually when you plug the plugin via "Plugman" or even stopping and restarting the server... the plugin give this error ... i use the latest build for your server version and does not conflict with other plugins;then i check for duplicate issues but I did not find it
virtually when you plug the plugin via "Plugman" or even stopping and restarting the server... the plugin give this error ... https://pastebin.com/jAJfmQLi 
Previously did not make this mistake but trying to put the plugin with back version but give this issue again ... please help me

**Comment by MiniDigger** [comment]
Don't use plugman, it's broken and protocollib (as many other plugins) are incompatible with it.
Please do a clean restart and then paste the error you are encountering again.

**Comment by heroeminecratti** [comment]
ok try

**Comment by heroeminecratti** [comment]
yes, thanks now begins again
