### ISSUE TITLE
Certain packet names assigned to the wrong ids

### ISSUE THREAD

**Issue by zeroeightysix** [aadnk/ProtocolLib#140]
According to my knowledge:

`PacketType.Play.Client.USE_ITEM` is assigned to ID `0x1F` which is the `Player Block Placement` packet ([wiki.vg page](http://wiki.vg/Protocol#Player_Block_Placement))
and
`PacketType.Play.Client.BLOCK_PLACE` is assigned to ID `0x20` which is the `Use Item` packet ([wiki.vg page](http://wiki.vg/Protocol#Use_Item))

Reference wiki and the [`PacketType`](https://github.com/aadnk/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/PacketType.java) class, line 299 & 300

I doubt this is intended. I've tested it myself, though I can't provide code because of it being in one of my actual plugins.

**Comment by dmulloy2** [comment]
Right, so the name is pretty ambiguous -- Spigot says one thing, while Wiki.vg says another. Since PacketTypes are done based on the Spigot class name, whatever they decide is reflected in ProtocolLib.
