### ISSUE TITLE
Can't write on Chat!

### ISSUE THREAD

**Issue by KrifixYT** [aadnk/ProtocolLib#141]
Hello! I have an error!
When i install a ProtocolLib plugin i cant write on chat, also type commands.
When i turn off plugin, it's ok, i can!
Please help!

**Comment by dmulloy2** [comment]
Run `/protocol dump` and paste the content with pastebin

**Comment by KrifixYT** [comment]
I dont know why, but, now i installed this plugin and its working!
Realy sorry for taking your time. Thanks!
