### ISSUE TITLE
Unable to set meta data of client sided entity

### ISSUE THREAD

**Issue by MrDienns** [aadnk/ProtocolLib#144]
I spawned an entity for one player specific by sending a spawn entity packet. After it's spawned, I want to change the meta data of this entity, however, I cannot figure out how to do so (too bad this project doesn't have any up to date docs or examples what so ever).

Below are severel things I tried, none of wich worked.

```WrapperPlayServerEntityMetadata metadataWrapper = new WrapperPlayServerEntityMetadata();
metadataWrapper.setEntityID(this.getID());
WrappedDataWatcher watcher = new WrappedDataWatcher();
watcher.setObject(2, Txt.parse(this.getCustomDisplayName()));
metadataWrapper.setMetadata(watcher.getWatchableObjects());
```

Results in:

```
java.lang.IllegalArgumentException: You cannot register objects without a watcher object!
```

This approach:

```WrapperPlayServerEntityMetadata metadataWrapper = new WrapperPlayServerEntityMetadata();
metadataWrapper.setEntityID(this.getID());
List<WrappedWatchableObject> metaData = new ArrayList<>();
metaData.add(new WrappedWatchableObject(2, Txt.parse(this.getCustomDisplayName())));
metadataWrapper.setMetadata(metaData);
```

Results in a crashing client:

https://image.prntscr.com/image/BLMelqEKQ7aMyjWj0v3Acg.png

Sorry to be making an issue for this, but again, this is a pretty complex API and the fact that it doesn't have ANY documentation (other than auto generated java-docs without any comments), nor any examples that aren't 4 year old, makes it close to impossible to use.

I would highly appreciate any help.

Thanks,

MrDienns

**Comment by FrankHeijden** [comment]
What's "this.getCustomDisplayName()"?

**Comment by MrDienns** [comment]
@FrankHeijden it returns the display name of the entity... The txt.parse function translates it with colorcodes.

**Comment by MrDienns** [comment]
This is still an issue.

Currently using this:

```
WrapperPlayServerEntityMetadata metadataWrapper = new WrapperPlayServerEntityMetadata();
metadataWrapper.setEntityID(this.getID());

WrappedDataWatcher metaWatcher = new WrappedDataWatcher();

metaWatcher.setObject(2, WrappedDataWatcher.Registry.get(String.class), "test");
metaWatcher.setObject(3, WrappedDataWatcher.Registry.get(Boolean.class), true, false);

metadataWrapper.setMetadata(metaWatcher.getWatchableObjects());

this.sendPacket(metadataWrapper.getHandle());
```
to try and update the player NPC name. Even trying to hide it doesn't seem to work at all. In which I try
```
WrapperPlayServerEntityMetadata metadataWrapper = new WrapperPlayServerEntityMetadata();
metadataWrapper.setEntityID(this.getID());

WrappedDataWatcher metaWatcher = new WrappedDataWatcher();

metaWatcher.setObject(2, WrappedDataWatcher.Registry.get(String.class), "");
metaWatcher.setObject(3, WrappedDataWatcher.Registry.get(Boolean.class), false, false);

metadataWrapper.setMetadata(metaWatcher.getWatchableObjects());

this.sendPacket(metadataWrapper.getHandle());
```
but no luck either. Packet is sent correctly, no server or client sided errors what so ever, but nothing is happening.

@aadnk @dmulloy2 Please guys, either help people out or write some proper documentation. Every example you ever find online is either outdated or simply not what you're looking for. Using this API is practically impossible.

**Comment by cyberpwnn** [comment]
Cough
```java
Field f = MinecraftReflection.class.getDeclaredField("cachedWatcherObject");
f.setAccessible(true);
f.set(null, true);
```
