### ISSUE TITLE
Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent

### ISSUE THREAD

**Issue by nathanthesnooper** [aadnk/ProtocolLib#150]
Log: https://pastebin.com/M9ZfFwG3
Dump: https://pastebin.com/PcL9r9mW
Error: https://pastebin.com/EJE1hBXS

Code:
```
ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter (this, PacketType.Play.Server.CHAT) {
	
	@Override
	public void onPacketSending (PacketEvent event) {
		
		if(blockedMessages.contains(event.getPacket().getChatComponents().read(0).getJson())) { // Error
			event.setCancelled(true);
		}
		
	}
	
});
```

Error occurs when a player recieves a chat message.

**Comment by dmulloy2** [comment]
Try using an older version of ProtocolLib that's closer to when 1.8 was released. You can check the version history on Spigot
