### ISSUE TITLE
OpenJDK8-OpenJ9 Error

### ISSUE THREAD

**Issue by B4TT3RY** [aadnk/ProtocolLib#162]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin _(Maybe)_
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
>https://pastebin.com/CAgcihZH
>https://pastebin.com/EQaT9hvu

Version:
>Paper 1.13.2 521 Build
>ProtocolLib 4.4.0 421 Build
>jdk8u202-b08_openj9-0.12.1-alpine

Description and relevant errors:
First log is just changed Hotspot to OpenJ9.
Second log is changed latest Dev Build.
Two errors occur on when i joined server.

Please tell me if you have more information.

**Comment by Artuto** [comment]
Did you fix this?
