### ISSUE TITLE
ConcurrentModificationException Kicks Player without Stack Trace

### ISSUE THREAD

**Issue by Kneesnap** [aadnk/ProtocolLib#176]
**Describe the bug**
This issue is a duplicate of #96 
Unfortunately, this is a rather difficult bug to provide information for.
Every so often, a player on my server will get kicked.
In the console, this message is present, examples seen below.

Unfortunately, this is difficult because there is no other information besides a CME occurred.
One of them has a ViaVersion warning, however I have no evidence that this is related, especially since most of the time there is no ViaVersion message.

**Expected behavior**
I expect a stack-trace to be printed, so it's possible to pin-point where the issue is coming from-- we have a lot of packet listeners and many of them we cannot disable without issue. We don't even know if it's from any of our code or if it's from another plugin, we have a bunch which all use ProtocolLib. On the off-chance this message is coming from ViaVersion, then this is not an issue with ProtocolLib (probably), but I think it remains to be shown if that is true.

**Screenshots**
![image](https://user-images.githubusercontent.com/6562913/82848807-07295680-9eaa-11ea-894a-4e3435ac6db0.png)

![image](https://user-images.githubusercontent.com/6562913/82848848-350e9b00-9eaa-11ea-8ea7-4ab7737be348.png)

**Version Info**
https://pastebin.com/J691UpBL

**Comment by MiniDigger** [comment]
start by updating protocollib to 4.5.1

**Comment by Kneesnap** [comment]
Will do. I'll post an update next time it happens, it might be a little
while before I can conclusively say if that makes the issue go away.

**Comment by Kneesnap** [comment]
Forgot to update this. The CME was occurring in vanilla packet writing logic.
