### ISSUE TITLE
Error from Console

### ISSUE THREAD

**Issue by CloudeLecaw** [aadnk/ProtocolLib#177]
![Snag_7cee931](https://user-images.githubusercontent.com/12080017/82937179-010da580-9f90-11ea-8f07-068ab80562d3.png)

**Comment by FeaturedSpace** [comment]
Are you using the latest version of ProtocolLib?

**Comment by CloudeLecaw** [comment]
i was using 451 - Updated now to Build454  mybe this fixed this allready?

Well i close the use if i dont see this again on my testserver :-)

**Comment by dmulloy2** [comment]
Looks like a Java 9 error, hence the standard disclaimer:

> ProtocolLib currently does not support Java 9. Until and unless Spigot updates past Java 8, ProtocolLib will only officially support Java 8

**Comment by CloudeLecaw** [comment]
This would explain it - im using Java 14.

Thanks for telling me. So this means i can irgnore this error right?

**Comment by MiniDigger** [comment]
yes, its save to be ignored. protocollib works fine on java 14
