### ISSUE TITLE
FieldAccessException

### ISSUE THREAD

**Issue by DrakMC** [aadnk/ProtocolLib#181]
I'm trying to use ProtocolLib to send a packet to a player to open a demo screen. However, it displays an error.

Code: https://pastebin.com/9GVNY5mj
Error: https://pastebin.com/bZDLPPeQ

I also tried this code: https://pastebin.com/dSUURDR3
But it shows me this error: https://pastebin.com/JA2haFzE

ProtocolLib Dump: https://pastebin.com/AVNzydGU

**Comment by MiniDigger** [comment]
well, the error is pretty clear. that packet doesnt contain ints nor bytes
take a look at the source
![https://i.imgur.com/mGvLCcj.png](https://i.imgur.com/mGvLCcj.png)
so you will have to update your code to reflect that, this is not a protocollib error.
