### ISSUE TITLE
Swimming pose

### ISSUE THREAD

**Issue by smaks6** [aadnk/ProtocolLib#184]
How to do swim positions with the protocollib?

**Comment by MWHunter** [comment]
if (player.inVehicle) {
                // Player cannot swim in a vehicle
                player.isSwimming = false;
            } else if (player.isSwimming) {
                // If the player is swimming, continue swimming if they were sprinting in the last tick and were touching water
                player.isSwimming = player.lastSprinting && player.wasTouchingWater;
            } else {
                // If the player isn't swimming already, swim if they were sprinting in the last tick, their eye is in the water, and they are touching water
                player.isSwimming = player.lastSprinting && player.wasEyeInWater && player.wasTouchingWater;
            }
