### ISSUE TITLE
ProtocolLib

### ISSUE THREAD

**Issue by uRyanxD** [aadnk/ProtocolLib#185]
**Describe the bug**
Protocol lib is generating lag times

**To Reproduce**
1. Download the plugin
2. Start you server

**Screenshots**
https://prnt.sc/y6w7nx

**Version Info**
ProtocolLib Version: ProtocolLib v4.5.1
Bukkit Version: 1.8.8-R0.1-SNAPSHOT
Server Version: git-PaperSpigot-0ed05fb8 (MC: 1.8.8)
Java Version: 1.8.0_275

**Comment by Titaniumtown** [comment]
Bruh, why are you using 1.8.8.
