### ISSUE TITLE
ProtocolLibrary.getProtocolManager(); return null?

### ISSUE THREAD

**Issue by GoldenGamerLP** [aadnk/ProtocolLib#189]
**Describe the bug**
If i want to get the ProtocollManager via the "ProtocolLibrary.getProtocolManager();" method, it always return null to me. Im using the latest dev Build (Current version: 4.7.0-SNAPSHOT-b521)

**To Reproduce**
1. Load the latest Dev Build (Current version: 4.7.0-SNAPSHOT-b521) and start the 1.17 Server
2. Follow the steps on the tutorial (Getting the ProtocollManager adding ProtocollLib as a depend in the plugin.yml)
3. Try to acces the "ProtocolLibrary.getProtocolManager();" method and try to use it
4. It throws you the error that the return of "ProtocolLibrary.getProtocolManager();" is null

**Expected behavior**
It should simply return the ProtocollManager

**Screenshots**
![image](https://user-images.githubusercontent.com/65727384/123312850-2836fd80-d529-11eb-8694-1a471d5394d9.png)
![image](https://user-images.githubusercontent.com/65727384/123312894-34bb5600-d529-11eb-8551-ccaabd36e285.png)
![image](https://user-images.githubusercontent.com/65727384/123312946-3e44be00-d529-11eb-84f1-a9a435252eb0.png)

**Version Info**
https://paste.helpch.at/sikosihixi.rb

**Additional context**
I used the onEnable method in the Plugin Main too, but that didnt change anything.

**Comment by MiniDigger** [comment]
dependdepend? what is that supposed to be? 
its just 'depend'
https://bukkit.fandom.com/wiki/Plugin_YAML

**Comment by GoldenGamerLP** [comment]
I already thought you would mention that, i saw the error later too, i corrected it, and it didnt work either

**Comment by Lori3f6** [comment]
It may caused by the incorrect configurations of the build tool. You may need to make sure that your build tool doesn't shade(include) classes of Protocollib in the packaged jar

**Comment by Withicality** [comment]
Check your pom.xml, make sure the scope is provided
![image](https://user-images.githubusercontent.com/54366349/156867224-79db588b-715a-4d93-93fc-0b232d2e2bdd.png)
