### ISSUE TITLE
Null when sending message using net.kyori.adventure.text.Component

### ISSUE THREAD

**Issue by markovav-official** [aadnk/ProtocolLib#191]
**Describe the bug**
I using this code: https://pastebin.com/EHKpRxYB
When I send message to player using net.kyori.adventure.text.Component, I recieve null on packet.getChatComponents().getValues().get(0)
How I can get this message anyway? I think it is incorrect behavior.

**To Reproduce**
1. Use this https://pastebin.com/EHKpRxYB
2. Send message to player using net.kyori.adventure.text.Component
3. Recieve packet
4. Recieve null on packet.getChatComponents().getValues().get(0)

**Expected behavior**
I want to recieve WrappedChatComponent but not null

**Version Info**
https://pastebin.com/UV0i1Z1B

**Error in console**
https://pastebin.com/Wcdv8w6Y

**Comment by MiniDigger** [comment]
getChatComponents uses vanilla components, not adventure components.

you want to create your own structure wrapper for accessing adventure components

**Comment by markovav-official** [comment]
How can I get the raw text (sended by plugin using adventure component) that is sent to the player?

**Comment by MiniDigger** [comment]
get the adventure component from the packet and use a PlainTextSerializer https://docs.adventure.kyori.net/serializer/plain.html

**Comment by markovav-official** [comment]
Thanks, I will try to do this
