### ISSUE TITLE
Support for Minecraft 1.0.0

### ISSUE THREAD

**Issue by 8PotatoChip8** [aadnk/ProtocolLib#193]
**Is your feature request related to a problem? Please describe.**
I am trying to create a Minecraft server that runs on version 1.0 but it seems as though ProtocolLib does not support that version

**Describe the solution you'd like**
I would like a versions of ProtocolLib to support Minecraft version 1.0.0

**Describe alternatives you've considered**
The alternative is to create a version that supports Minecraft versions below 1.0.0 and above

**Additional context**
N/A

**Comment by lokka30** [comment]
Hey, whilst they're at it, could you guys add Beta 1.3 support?

**Comment by CrazyWords1** [comment]
xD)))

**Comment by dmulloy2** [comment]
well memed lol

**Comment by 8PotatoChip8** [comment]
Bruh, why you close this? I am genuinely trying to run a Minecraft server on version 1.0.0. The problem is that ProtocolLib doesn't seem to work on that version, I am trying to use TCPShield to hide my personal IP address as I am hosting the server on my home internet connection. No memes here.

**Comment by Rattlyy** [comment]
LMFAO

**Comment by dmulloy2** [comment]
bro invite me to your hamachi

**Comment by 8PotatoChip8** [comment]
Yall are funny I get it, but I am seriously looking for an answer. Should I go find another solution for this or could you guys help?

**Comment by Rattlyy** [comment]
try implementing your own packet listener

**Comment by 8PotatoChip8** [comment]
Right, but I'm looking to do this for essentially free. If I were to implement a packet listener I would have to do it on some VPS to hide my IP address, no? And I don't know anyone handing out free VPS'

**Comment by Rattlyy** [comment]
> Right, but I'm looking to do this for essentially free. If I were to implement a packet listener I would have to do it on some VPS to hide my IP address, no? And I don't know anyone handing out free VPS'

tf what

**Comment by 8PotatoChip8** [comment]
Idk man, you think I know anything?

**Comment by Rattlyy** [comment]
> Idk man, you think I know anything?

do you like.. know java?

**Comment by 8PotatoChip8** [comment]
As a programming language? Not really

**Comment by Rattlyy** [comment]
> As a programming language? Not really 

And without knowing java you think you'll be able to make something in a totally unsupported and extremely old minecraft version?

**Comment by 8PotatoChip8** [comment]
Yes, I was planning on it. I just slap stuff together and try to make it work.

**Comment by 8PotatoChip8** [comment]
I've had a fully working server running 1.0.0 before with plugins and all, the problem is that I don't want to hand out my home IP address online. Yes it will be behind a domain, but that doesn't hide it

**Comment by Rattlyy** [comment]
> I've had a fully working server running 1.0.0 before with plugins and all, the problem is that I don't want to hand out my home IP address online. Yes it will be behind a domain, but that doesn't hide it

use tcpshield or noip to hide ur ip

**Comment by 8PotatoChip8** [comment]
I am trying to use TCPShield, thats why I created this feature request.

**Comment by 8PotatoChip8** [comment]
TCPShield needs ProtocolLib, but ProtocolLib is not supported on version 1.0.0 , I don't think

**Comment by 8PotatoChip8** [comment]
And to my knowledge noip is the same as using a domain that I plan on using anyway, people can still just ping the domain and get the ip address

**Comment by Rattlyy** [comment]
> TCPShield needs ProtocolLib, but ProtocolLib is not supported on version 1.0.0 , I don't think

tcpshield needs protocollib to get the real ip of people, his plugin is not required

**Comment by 8PotatoChip8** [comment]
"When using Spigot / CraftBukkit, ProtocolLib needs to be installed."

**Comment by Rattlyy** [comment]
> "When using Spigot / CraftBukkit, ProtocolLib needs to be installed."

I run a network with tcpshield, protocollib is useless

**Comment by 8PotatoChip8** [comment]
oh, I see.

**Comment by 8PotatoChip8** [comment]
I understand it now
