### ISSUE TITLE
Example of listening for a custom packet

### ISSUE THREAD

**Issue by alecgorge** [aadnk/ProtocolLib#40]
How do you listen for a custom packet?

I would like to access a custom packet that uses an otherwise unused ID. This packet is sent before the handshake or anything else is sent if that matters.

Simply hardcoding the packet ID into something like this doesn't work:

```
new PacketType(PacketType.Protocol.HANDSHAKING, PacketType.Sender.CLIENT, 0x47, 0x47)
```

 I get an error like this:

```
Unsupported client packet ID in current Minecraft version: UNREGISTERED [HANDSHAKING, CLIENT, 71, legacy: 71]
```

**Comment by ramaroberto** [comment]
Hi! Sorry for resurrecting this, but I'm trying to listen a custom packet using ProtocolLib in LOGIN (I modified the client to sent it) and I'm not having too much luck trying the things posted here. 

There were any major changes in the API? It's possible to do this yet?

Thanks in advance!
