### ISSUE TITLE
Unable to uninject logged off player.

### ISSUE THREAD

**Issue by Kainzo** [aadnk/ProtocolLib#79]
http://pastie.org/private/4u6kzw8pebgkbd5mcdsneq

**Comment by dmulloy2** [comment]
That line is:
````java
this.updated = null;
````

Are you using the latest version from my jenkins?

**Comment by Kainzo** [comment]
Version was as of 1/2/2015 @ 7:45PM CST

**Comment by dmulloy2** [comment]
Use http://ci.shadowvolt.com/job/ProtocolLib/71/ and see if it's fixed.

**Comment by Kainzo** [comment]
Ill give it a test - I will state that this is no longer happening (it may have been fixed by spigot or you)
