### ISSUE TITLE
Root tag must be a named compound tag

### ISSUE THREAD

**Issue by Kainzo** [aadnk/ProtocolLib#80]
https://www.irccloud.com/pastebin/h6LcJFWa
Version is from 1/2/2015 @ 7pm CST

 http://herocraftonline.com/main/threads/backpack-not-saving-custom-items.56021/
http://i.imgur.com/P86pPm7.png < the item attempting to be stored.
Developers said that the NBT / item stuff was handed to you guys to serialize - if this is the wrong issue tracker, I apologize!

**Comment by dmulloy2** [comment]
The StreamSerializer passes the call to Minecraft's PacketDataSerializer, which is where the error occurs.  There isn't anything I can do with ProtocolLib to fix the error, but ensure that the root tag is a named compound tag.

Also, the new issue tracker is here, for future issues: https://github.com/dmulloy2/ProtocolLib/issues

**Comment by Kainzo** [comment]
Odd... tagging @Mung3r -- since hes the dev of Backpacks
