### ISSUE TITLE
ProtocolLib Stacktrace

### ISSUE THREAD

**Issue by cn0** [aadnk/ProtocolLib#85]
This Stacktrace occures every time, I try to catch an outgoing Motd Packet:
https://gist.github.com/cn0/8f987057bd94e97fca29

**Comment by dmulloy2** [comment]
This shouldn't happen unless there are other errors. Are there any other errors with ProtocolLib?

**Comment by dmulloy2** [comment]
Should be fixed in https://github.com/dmulloy2/ProtocolLib/commit/889d1f6bc4de03bde95c1b86e646e197ce4b568b
