### ISSUE TITLE
Flood in console from the plugin

### ISSUE THREAD

**Issue by MrTrojan** [aadnk/ProtocolLib#90]
Hello, I have a problem with your plugin, there is a constant flood of your plugin.

015-06-23 09:07:13 [WARNING] [ProtocolLib] [ProxyPacketInjector] Timeout: Unknown origin java.io.DataInputStream@3984d48b for packet Packet250CustomPayload$$EnhancerByCGLIB$$54628f7f[23, legacy: 250]. Are you using GamePhase.LOGIN?

How to fix it?

Sorry, if it is not clear writing, I am writing to russian Google Translator.

**Comment by dmulloy2** [comment]
What versions of ProtocolLib and Spigot are you using?

**Comment by MrTrojan** [comment]
I'm using the latest version of your plugin. I did not spigot and MCPC+ 1.6.4.

**Comment by dmulloy2** [comment]
Try the latest build from here: http://ci.shadowvolt.com/job/ProtocolLib/

Worst case scenario, you'll get a huge error that you should paste using pastebin.

**Comment by MrTrojan** [comment]
Download and still are mistakes, but they have already come to the chat player.

http://pastebin.com/0xnJSWjT
http://prntscr.com/7m8bl1

More delays at the start of weapons mod fashion Flans Mod.
