### ISSUE TITLE
[TinyProtocol] Method doesn't exist

### ISSUE THREAD

**Issue by airidas338** [aadnk/ProtocolLib#92]
https://github.com/aadnk/ProtocolLib/blob/master/modules/TinyProtocol/src/main/java/com/comphenix/tinyprotocol/TinyProtocol.java#L57
I decompiled ServerConnection.class and there is no such method. There are no even static methods.
Platform: Spigot 1.8.7

**Comment by dmulloy2** [comment]
Does this cause any errors when using TinyProtocol?

**Comment by airidas338** [comment]
It should cause NullPointerException in here: https://github.com/aadnk/ProtocolLib/blob/master/modules/TinyProtocol/src/main/java/com/comphenix/tinyprotocol/TinyProtocol.java#L187

And break synchronization in here:
https://github.com/aadnk/ProtocolLib/blob/master/modules/TinyProtocol/src/main/java/com/comphenix/tinyprotocol/TinyProtocol.java#L112

[I didn't checked if it works, just noticed it by looking at code]
