### ISSUE TITLE
Get player from PacketLoginInStart

### ISSUE THREAD

**Issue by SkymaxPlay** [aadnk/ProtocolLib#97]
Hello,
I have a problem, How to send packet to player when I received PacketLoginInStart?
PacketLoginInStart sending to server only GameProfile. Can I use GameProfile to create EntityPlayer,next create PlayerConnection and send packet using PlayerConnection?
How to do it ProtocolLib that can get player from this packet?

**Comment by dmulloy2** [comment]
As far as I know, there isn't a way to do this. Why do you need to send a packet when you receive the login start packet? Seems like an [XY problem](http://xyproblem.info/).

**Comment by SkymaxPlay** [comment]
Because I want create system  auth when offline mode. I saw this using ProtocolLib but I want do this using normal packets etc.

**Comment by dmulloy2** [comment]
I'm confused. What exactly are you trying to do? And if you saw an example using ProtocolLib, why not use it?

**Comment by SkymaxPlay** [comment]
Because I don't like creating plugins with ProtocolLib, I creating plugins which does not need any other plug-ins

**Comment by dmulloy2** [comment]
Unless you already have your own injection system, I would suggest using [TinyProtocol](https://github.com/dmulloy2/ProtocolLib/tree/master/modules/TinyProtocol/src/main/java/com/comphenix/tinyprotocol). From there, the receiver/sender will probably be null in the login/status phase, but you could probably do something with the [channel](http://netty.io/4.0/api/io/netty/channel/Channel.html). Of interest would probably be the ````write(Object)```` and ````writeAndFlush(Object)```` methods.
