### ISSUE TITLE
Auto-Updater can not disable

### ISSUE THREAD

**Issue by Heddo** [aadnk/ProtocolLib#99]
Auto-Updater can not disable.

Add into config to turn off the Auto-Updater

http://hastebin.com/cahegayewo.xml

**Comment by Paulomart** [comment]
I'm in the same project as @Heddo:

Our problem is that we are building protocollib on our on Jenkins and updating it with other software. We don't need to check for updates because they will have the wrong version number either way. Currently there is no way to disable this in protocollib.
